version: 1.2.7
workflows:
   - subclass: NFL
     primaryDescriptorPath: /nextflow.config
     name: StellarPGx
     authors:
      - name: David Twesigomwe
        email: david.twesigomwe@wits.ac.za
     publish: True
