version: 1.2
workflows:
   - name: StellarPGx
     subclass: NFL
     primaryDescriptorPath: /nextflow.config
     authors:
      - name: David Twesigomwe
        email: david.twesigomwe@wits.ac.za
     publish: True
