
version: 1.2.6.1
workflows:
  - subclass: NFL
    primaryDescriptorPath: /nextflow.config
    name: StellarPGx
    authors:
      - name: 'David Twesigomwe'
        email: 'twesigomwedavid@gmail.com'
